name = "UHD"
uuid = "6c8ab8da-e7d8-41d6-b41d-f7ebe848a741"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
julia = "1"
